language: node_js
node_js: "lts/*"
os: linux
services:
  - xvfb
before_install:
  - 'export PATH=./node_modules/.bin:$PATH'
  - 'npm install -g typescript'
  - 'npm install -g vsce'
install:
  - 'npm ci'
  # https://github.com/travis-ci/travis-ci/issues/8813
  - 'rm -f ./node_modules/.bin/which'
  - 'vsce package'
script:
  - 'npm test --silent'
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]]; then
    sonar-scanner;
    fi
cache:
  directories:
    - "$HOME/.npm"
env: DISPLAY=:99
branches:
  except:
    - /^dependabot.*$/
addons:
  sonarcloud:
    organization: "redhat-developer"
    branches:
      - master